name: styled_text
description: With this package, you can highlight words and create specific styles using regular expressions.
version: 0.0.1
author: NaoPlus <info@naoplus.ru>
homepage: https://github.com/Syaba999/styled_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

